const { contextBridge, ipcRenderer } = require('electron');

try { ipcRenderer.send('startup:preloadEntry'); } catch {}

contextBridge.exposeInMainWorld('beehive', {
  getVersion: () => ipcRenderer.invoke('app:getVersion'),
  startupDebugEnabled: process.argv.includes('--startup-debug') || process.env.BEEHIVE_STARTUP_DEBUG === '1',
  performanceDebugEnabled: process.argv.includes('--scroll-debug') || process.argv.includes('--startup-debug') || process.env.BEEHIVE_SCROLL_DEBUG === '1' || process.env.BEEHIVE_STARTUP_DEBUG === '1',
  startupDebugLog: (label, details) => ipcRenderer.invoke('startup:debugLog', { label, details }),
  startupDebugState: () => ipcRenderer.invoke('startup:debugState'),
  getPlaybackState: () => ipcRenderer.invoke('playback-state:get'),
  savePlaybackStateSync: (state) => ipcRenderer.sendSync('playback-state:saveSync', state),
  updatePlaybackTransportSync: (state) => ipcRenderer.sendSync('playback-state:updateTransportSync', state),
  // Same handler without blocking the renderer; used for periodic saves.
  updatePlaybackTransport: (state) => ipcRenderer.send('playback-state:updateTransportSync', state),
  setPlaybackProtectedPath: (trackPath) => ipcRenderer.send('playback:protectPath', trackPath || ''),
  getConfig: () => ipcRenderer.invoke('config:get'),
  saveUiState: (state) => ipcRenderer.invoke('config:saveUiState', state || {}),
  listDevices: () => ipcRenderer.invoke('devices:list'),
  setDeviceDestination: (deviceId, destinationPath) => ipcRenderer.invoke('devices:setDestination', { deviceId, destinationPath }),
  listAudioOutputs: () => ipcRenderer.invoke('audio-output:list'),
  setAudioOutput: (choice) => ipcRenderer.invoke('audio-output:set', choice && typeof choice === 'object' ? choice : { sink: String(choice || '') }),
  sendTracksToDevice: (device, tracks) => ipcRenderer.invoke('devices:sendTracks', { device, tracks }),
  onDeviceTransferProgress: (cb) => {
    const listener = (_evt, payload) => cb(payload);
    ipcRenderer.on('devices:transferProgress', listener);
    return () => ipcRenderer.removeListener('devices:transferProgress', listener);
  },
  getDiscordPresenceSettings: () => ipcRenderer.invoke('discord-presence:getSettings'),
  setDiscordPresenceActivityType: (activityType) => ipcRenderer.invoke('discord-presence:setActivityType', { activityType }),
  restartDiscordPresence: () => ipcRenderer.invoke('discord-presence:restart'),
  setDiscordPresenceEnabled: (enabled) => ipcRenderer.invoke('discord-presence:setEnabled', !!enabled),
  mprisUpdate: (payload) => ipcRenderer.invoke('mpris:update', payload || {}),
  onMprisCommand: (cb) => { const listener = (_evt, command) => cb(command); ipcRenderer.on('mpris:command', listener); return () => ipcRenderer.removeListener('mpris:command', listener); },
  getGpuAcceleration: () => ipcRenderer.invoke('graphics:getGpuAcceleration'),
  setGpuAcceleration: (enabled) => ipcRenderer.invoke('graphics:setGpuAcceleration', !!enabled),
  getCustomCss: () => ipcRenderer.invoke('custom-css:get'),
  setCustomCss: (css) => ipcRenderer.invoke('custom-css:set', { css: String(css || '') }),
  chooseCustomCss: () => ipcRenderer.invoke('custom-css:choose'),
  clearCustomCss: () => ipcRenderer.invoke('custom-css:clear'),
  importTheme: () => ipcRenderer.invoke('theme:import'),
  exportTheme: (payload) => ipcRenderer.invoke('theme:export', payload || {}),
  listThemeFolder: () => ipcRenderer.invoke('themes:list'),
  openThemeFolder: () => ipcRenderer.invoke('themes:openFolder'),
  seedStockThemes: (themes) => ipcRenderer.invoke('themes:seedStock', themes),
  getThemeMeta: () => ipcRenderer.invoke('theme:meta'),
  listPlugins: () => ipcRenderer.invoke('plugins:list'),
  setPluginEnabled: (id, enabled) => ipcRenderer.invoke('plugins:setEnabled', { id, enabled }),
  openPluginsFolder: () => ipcRenderer.invoke('plugins:openFolder'),
  installPluginFolder: () => ipcRenderer.invoke('plugins:installFolder'),
  getPluginSettings: (id) => ipcRenderer.invoke('plugins:getSettings', { id }),
  setPluginSettings: (id, settings) => ipcRenderer.invoke('plugins:setSettings', { id, settings }),
  runPlugin: (source, id) => ipcRenderer.invoke('plugins:run', { source, id }),
  scrobbleStatus: () => ipcRenderer.invoke('scrobble:status'),
  scrobbleConfig: () => ipcRenderer.invoke('scrobble:config'),
  saveScrobbleSettings: (patch) => ipcRenderer.invoke('scrobble:save', patch || {}),
  lastfmBeginAuth: () => ipcRenderer.invoke('scrobble:lastfmBegin'),
  lastfmFinishAuth: () => ipcRenderer.invoke('scrobble:lastfmFinish'),
  scrobbleStarted: (track) => ipcRenderer.invoke('scrobble:started', track || {}),
  scrobbleNowPlaying: (track) => ipcRenderer.invoke('scrobble:nowPlaying', track || {}),
  scrobbleSubmit: (track) => ipcRenderer.invoke('scrobble:submit', track || {}),
  getSimilarArtists: (artistName) => ipcRenderer.invoke('music:similarArtists', artistName),
  addFolder: () => ipcRenderer.invoke('config:addFolder'),
  removeFolder: (folder) => ipcRenderer.invoke('config:removeFolder', folder),
  showFileInBrowser: (filePath) => ipcRenderer.invoke('file:showInBrowser', filePath),
  deleteTracksFromDisk: (filePaths) => ipcRenderer.invoke('tracks:deleteFromDisk', filePaths),
  startNativeFileDrag: (filePaths) => ipcRenderer.send('files:startDrag', Array.isArray(filePaths) ? filePaths : [filePaths]),

  getCachedLibrary: (options) => ipcRenderer.invoke('library:getCached', options || {}),
  clearLibraryCacheNow: () => ipcRenderer.invoke('library:clearCacheNow'),
  // Startup: did anything change in the library folders while Hive was closed?
  libraryStartupCheck: () => ipcRenderer.invoke('library:startupCheck'),
  scanLibrary: (options) => ipcRenderer.invoke('library:scan', options),
  scanChangedLibrary: (paths) => ipcRenderer.invoke('library:scanChanged', paths),
  cancelLibraryScan: () => ipcRenderer.invoke('library:cancelScan'),
  searchLibraryDatabase: (text, limit) => ipcRenderer.invoke('library:searchDatabase', { text, limit }),
  getTaskStatus: () => ipcRenderer.invoke('library:taskStatus'),
  betaSecurityAudit: () => ipcRenderer.invoke('beta:securityAudit'),
  betaLibraryHealth: () => ipcRenderer.invoke('beta:libraryHealth'),
  betaEnvironmentAudit: () => ipcRenderer.invoke('beta:environmentAudit'),
  betaDatabaseHealth: () => ipcRenderer.invoke('beta:databaseHealth'),
  getDiagnosticLogs: () => ipcRenderer.invoke('diagnostics:getLogs'),
  startDiagnostics: () => ipcRenderer.invoke('diagnostics:start'),
  finishDiagnostics: () => ipcRenderer.invoke('diagnostics:finish'),
  getDiagnosticsStatus: () => ipcRenderer.invoke('diagnostics:status'),
  diagnosticMark: (phase, detail) => ipcRenderer.invoke('diagnostics:mark', phase, detail),
  openDiagnosticsFolder: () => ipcRenderer.invoke('diagnostics:open-folder'),
  writeFavoritesPipelineDiagnostic: (report) => ipcRenderer.invoke('diagnostics:writeFavoritesPipeline', report || {}),
  getArtworkProviders: () => ipcRenderer.invoke('artwork:providers'),
  refreshLovedLibrary: () => ipcRenderer.invoke('library:refreshLoved'),
  needsLovedRefresh: () => ipcRenderer.invoke('library:needsLovedRefresh'),
  onScanProgress: (cb) => {
    const listener = (_evt, payload) => cb(payload);
    ipcRenderer.on('library:scanProgress', listener);
    return () => ipcRenderer.removeListener('library:scanProgress', listener);
  },
  onScanTrack: (cb) => {
    const listener = (_evt, track) => cb(track);
    ipcRenderer.on('library:scanTrack', listener);
    return () => ipcRenderer.removeListener('library:scanTrack', listener);
  },
  onTagProgress: (cb) => {
    const listener = (_evt, payload) => cb(payload);
    ipcRenderer.on('library:tagProgress', listener);
    return () => ipcRenderer.removeListener('library:tagProgress', listener);
  },
  queueMetadataSave: (jobs) => ipcRenderer.send('metadata:saveBatch', Array.isArray(jobs) ? jobs : []),
  onLibraryFilesChanged: (cb) => {
    const listener = (_evt, payload) => cb(payload);
    ipcRenderer.on('library:filesChanged', listener);
    return () => ipcRenderer.removeListener('library:filesChanged', listener);
  },

  toggleLove: (trackPath, value) => ipcRenderer.invoke('track:toggleLove', trackPath, value),
  setLove: (trackPaths, loved) => ipcRenderer.invoke('tracks:setLove', trackPaths, loved),
  artistImage: (artist) => ipcRenderer.invoke('artwork:artistImage', artist),
  readLove: (trackPath) => ipcRenderer.invoke('track:readLove', trackPath),
  readLoves: (paths) => ipcRenderer.invoke('tracks:readLove', paths),
  recordPlay: (trackPath, meta) => ipcRenderer.invoke('track:recordPlay', trackPath, meta),
  recordListeningEvent: (payload) => ipcRenderer.invoke('listening:record', payload || {}),
  getYearlyWrapData: (year) => ipcRenderer.invoke('yearly-wrap:getData', year),
  getYearlyWrapYears: () => ipcRenderer.invoke('yearly-wrap:getYears'),
  chooseMusicBeeWrappedImport: () => ipcRenderer.invoke('yearly-wrap:chooseMusicBeeImport'),
  importMusicBeeWrapped: (archivePath) => ipcRenderer.invoke('yearly-wrap:importMusicBee', archivePath),
  getMusicBeeWrappedState: () => ipcRenderer.invoke('yearly-wrap:getMusicBeeState'),
  chooseHiveWrappedExport: () => ipcRenderer.invoke('yearly-wrap:chooseWrappedExport'),
  exportHiveWrapped: (destinationPath) => ipcRenderer.invoke('yearly-wrap:exportWrapped', destinationPath),
  replaceMusicBeePlayCounts: () => ipcRenderer.invoke('yearly-wrap:replacePlayCounts'),
  forceEmbedPlayCounts: (paths) => ipcRenderer.invoke('stats:forceEmbedPlayCounts', paths || null),
  openYearlyWrap: (year, theme) => ipcRenderer.invoke('yearly-wrap:open', year, theme || null),
  pushYearlyWrapTheme: (theme) => ipcRenderer.invoke('yearly-wrap:pushTheme', theme || null),
  onYearlyWrapTheme: (callback) => ipcRenderer.on('yearly-wrap:theme', (_evt, theme) => callback(theme)),
  saveYearlyWrapImage: (payload) => ipcRenderer.invoke('yearly-wrap:saveImage', payload || {}),
  copyYearlyWrapImage: (dataUrl) => ipcRenderer.invoke('yearly-wrap:copyImage', dataUrl || ''),
  // Despite the name, also the shared source for Hive's own logo image data
  // used by the main renderer's brand button/About dialog -- see the
  // handler's comment in main.js.
  getYearlyWrapBrandIcon: () => ipcRenderer.invoke('yearly-wrap:getBrandIcon'),
  clearPlayCounts: () => ipcRenderer.invoke('stats:clearPlayCounts'),
  setEmbedPlayCounts: (enabled) => ipcRenderer.invoke('stats:setEmbedPlayCounts', !!enabled),
  getEmbedPlayCounts: () => ipcRenderer.invoke('stats:getEmbedPlayCounts'),
  getHistory: () => ipcRenderer.invoke('history:get'),
  setRating: (trackPath, rating) => ipcRenderer.invoke('track:setRating', trackPath, rating),
  setRatings: (trackPaths, rating) => ipcRenderer.invoke('tracks:setRatings', trackPaths, rating),
  readRatings: (paths) => ipcRenderer.invoke('tracks:readRatings', paths),
  updateCachedLoves: (loves) => ipcRenderer.invoke('tracks:updateCachedLoves', loves),
  updateCachedRatings: (ratings) => ipcRenderer.invoke('tracks:updateCachedRatings', ratings),
  embedRatings: (tracks) => ipcRenderer.invoke('tracks:embedRatings', tracks),
  readTags: (trackPath) => ipcRenderer.invoke('track:readTags', trackPath),
  hasEmbeddedArtwork: (trackPath) => ipcRenderer.invoke('track:hasEmbeddedArtwork', trackPath),
  searchLyrics: (query) => ipcRenderer.invoke('lyrics:search', query),
  writeTags: (trackPath, tags) => ipcRenderer.invoke('track:writeTags', trackPath, tags),
  musicBrainzGetReleaseDetails: (releaseId) => ipcRenderer.invoke('musicbrainz:getReleaseDetails', releaseId),
  musicBrainzSearchReleases: (query) => ipcRenderer.invoke('musicbrainz:searchReleases', query),
  metadataBulkWriteStart: (label) => ipcRenderer.invoke('metadata:bulkWriteStart', label),
  metadataBulkWriteEnd: (label) => ipcRenderer.invoke('metadata:bulkWriteEnd', label),
  chooseCover: () => ipcRenderer.invoke('cover:choose'),
  writeArtwork: (trackPath, imagePath, artworkMeta) => ipcRenderer.invoke('track:writeArtwork', trackPath, imagePath, artworkMeta),
  modifyArtwork: (trackPath, operation, options = {}) => ipcRenderer.invoke('track:modifyArtwork', trackPath, operation, options),
  removeArtwork: (trackPath) => ipcRenderer.invoke('track:removeArtwork', trackPath),
  searchItunes: (query) => ipcRenderer.invoke('cover:searchItunes', query),
  searchInternetCover: (query) => ipcRenderer.invoke('cover:searchInternet', query),
  loadTemporaryCover: (url) => ipcRenderer.invoke('cover:loadTemporary', url),
  downloadSearchCover: (url) => ipcRenderer.invoke('cover:downloadSearchResult', url),
  downloadItunesCover: (url) => ipcRenderer.invoke('cover:downloadItunes', url),
  pasteCover: () => ipcRenderer.invoke('cover:paste'),
  saveImageFile: (imagePath) => ipcRenderer.invoke('cover:saveImage', imagePath),
  saveDataUrlImage: (dataUrl, filename) => ipcRenderer.invoke('cover:saveDataUrlImage', dataUrl, filename),
  copyCover: (coverFile) => ipcRenderer.invoke('cover:copy', coverFile),
  saveCover: (coverFile) => ipcRenderer.invoke('cover:save', coverFile),
  getPlaylists: () => ipcRenderer.invoke('playlists:get'),
  savePlaylist: (playlist) => ipcRenderer.invoke('playlists:save', playlist),
  deletePlaylist: (id) => ipcRenderer.invoke('playlists:delete', id),
  choosePlaylistImportFile: () => ipcRenderer.invoke('playlists:chooseImportFile'),
  exportPlaylistM3U: (payload) => ipcRenderer.invoke('playlists:exportM3U', payload),
  importSpotifyPlaylist: (input) => ipcRenderer.invoke('playlists:importSpotify', input),
  spotifyStatus: () => ipcRenderer.invoke('spotify:status'),
  spotifyLaunch: () => ipcRenderer.invoke('spotify:launch'),
  spotifyLogin: () => ipcRenderer.invoke('spotify:login'),
  spotifyCommand: (command) => ipcRenderer.invoke('spotify:command', command),
  spotifyCacheArtwork: (urls) => ipcRenderer.invoke('spotify:cacheArtwork', urls),
  podcastSearch: (query) => ipcRenderer.invoke('podcast:search', query),
  podcastFeed: (url) => ipcRenderer.invoke('podcast:feed', url),
  getPodcastFavorites: () => ipcRenderer.invoke('podcasts:favorites:get'),
  togglePodcastFavorite: (favorite) => ipcRenderer.invoke('podcasts:favorites:toggle', favorite || {}),
  onSpotifyState: (cb) => { const listener = (_evt, payload) => cb(payload); ipcRenderer.on('spotify:state', listener); return () => ipcRenderer.removeListener('spotify:state', listener); },
  onSpotifyPlaylist: (cb) => { const listener = (_evt, payload) => cb(payload); ipcRenderer.on('spotify:playlist', listener); return () => ipcRenderer.removeListener('spotify:playlist', listener); },
  musicBrainzSearchReleaseGroups: (query) => ipcRenderer.invoke('musicbrainz:searchReleases', query),
  musicBrainzIdentify: (query) => ipcRenderer.invoke('musicbrainz:identify', query),

  gstreamerStatus: () => ipcRenderer.invoke('gstreamer:status'),
  validateAudioForPlayback: (trackPath) => ipcRenderer.invoke('audio:validate', trackPath),
  scanAudioIntegrityLibrary: (paths) => ipcRenderer.invoke('audio:integrity-scan', Array.isArray(paths) ? paths : []),
  cancelAudioIntegrityScan: () => ipcRenderer.invoke('audio:integrity-scan-cancel'),
  getAudioIntegrityScanCheckpoint: () => ipcRenderer.invoke('audio:integrity-scan-checkpoint'),
  resumeAudioIntegrityScan: () => ipcRenderer.invoke('audio:integrity-scan-resume'),
  startOverAudioIntegrityScan: () => ipcRenderer.invoke('audio:integrity-scan-start-over'),
  window: {
    minimize: () => ipcRenderer.invoke('window:minimize'),
    maximize: () => ipcRenderer.invoke('window:maximize'),
    close: () => ipcRenderer.invoke('window:close'),
    isMaximized: () => ipcRenderer.invoke('window:is-maximized'),
    getThemeBar: () => ipcRenderer.invoke('window:theme-bar:get'),
    setThemeBar: (enabled) => ipcRenderer.invoke('window:theme-bar:set', !!enabled),
    onMaximizedChanged: (cb) => { const listener = (_evt, value) => cb(!!value); ipcRenderer.on('window:maximized-changed', listener); return () => ipcRenderer.removeListener('window:maximized-changed', listener); }
  },
  repairLoveMetadata: (items) => ipcRenderer.invoke('audio:integrity-repair-love', Array.isArray(items) ? items : []),
  repairCorruptAudioFile: (item) => ipcRenderer.invoke('audio:integrity-repair-corrupt', item || {}),
  generateAudioIntegrityReport: (result) => ipcRenderer.invoke('audio:integrity-report', result || null),
  openAudioIntegrityReports: () => ipcRenderer.invoke('audio:integrity-open-reports'),
  getFirstScanIntegrityState: () => ipcRenderer.invoke('audio:first-scan-integrity-state'),
  openCrashReports: () => ipcRenderer.invoke('diagnostics:openCrashReports'),
  crashReportCount: () => ipcRenderer.invoke('diagnostics:crashReportCount'),
  checkForUpdates: () => ipcRenderer.invoke('updates:check'),
  downloadUpdate: () => ipcRenderer.invoke('updates:download'),
  installUpdate: () => ipcRenderer.invoke('updates:install'),
  getUpdateStatus: () => ipcRenderer.invoke('updates:status'),
  onUpdateStatusChanged: (cb) => { const listener = (_evt, status) => cb(status); ipcRenderer.on('updates:statusChanged', listener); return () => ipcRenderer.removeListener('updates:statusChanged', listener); },
  onFirstScanIntegrityComplete: (cb) => { const listener = (_evt, payload) => cb(payload); ipcRenderer.on('audio:first-scan-integrity-complete', listener); return () => ipcRenderer.removeListener('audio:first-scan-integrity-complete', listener); },
  onAudioIntegrityScanProgress: (cb) => { const listener = (_evt, payload) => cb(payload); ipcRenderer.on('audio:integrity-scan-progress', listener); return () => ipcRenderer.removeListener('audio:integrity-scan-progress', listener); },
  gstreamerRestart: () => ipcRenderer.invoke('gstreamer:restart'),
  gstreamerCommand: (command) => ipcRenderer.send('gstreamer:command', command),
  onGstreamerEvent: (cb) => { const listener = (_evt, payload) => cb(payload); ipcRenderer.on('gstreamer:event', listener); return () => ipcRenderer.removeListener('gstreamer:event', listener); },

  fileUrl: (absPath) => `mbfile://${encodeURIComponent(absPath)}`,
  coverUrl: (coverFile) => (coverFile ? `mbcover://${encodeURIComponent(coverFile)}` : null)
});
